//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkAge_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.CommentDetails = new HashSet<CommentDetail>();
        }
    
        public int CommentID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Comment1 { get; set; }
        public Nullable<int> Star { get; set; }
        public Nullable<int> GP_Quantity { get; set; }
        public Nullable<int> BP_Quantity { get; set; }
        public Nullable<int> MemberID { get; set; }
        public byte[] CommentPicture { get; set; }
        public Nullable<bool> Display { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentDetail> CommentDetails { get; set; }
    }
}
