//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkAge_1._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrinkAgeEntities : DbContext
    {
        public DrinkAgeEntities()
            : base("name=DrinkAgeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryDetail> CategoryDetails { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FavoriteProduct> FavoriteProducts { get; set; }
        public virtual DbSet<FavoriteStore> FavoriteStores { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberACHV> MemberACHVs { get; set; }
        public virtual DbSet<MemPointDetail> MemPointDetails { get; set; }
        public virtual DbSet<Order_Detail> Order_Details { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Points_Mall> Points_Malls { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSizePrice> ProductSizePrices { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<StoreDiscount> StoreDiscounts { get; set; }
        public virtual DbSet<StoreIngredientPrice> StoreIngredientPrices { get; set; }
        public virtual DbSet<Sugar> Sugars { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Temperature> Temperatures { get; set; }
        public virtual DbSet<CommentDetail> CommentDetails { get; set; }
    }
}
