//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkAge_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int OrderDetail_ID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public int SizeID { get; set; }
        public int SugarID { get; set; }
        public int TemperatureID { get; set; }
        public Nullable<int> IngredientID { get; set; }
        public Nullable<int> StoreDiscountID { get; set; }
        public Nullable<int> PointItemID { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Order Order { get; set; }
        public virtual Points_Mall Points_Mall { get; set; }
        public virtual Size Size { get; set; }
        public virtual StoreDiscount StoreDiscount { get; set; }
        public virtual Sugar Sugar { get; set; }
        public virtual Temperature Temperature { get; set; }
    }
}
